### ISSUE TITLE
Update repo to be compatible with latest Kubuntu and KDE

### ISSUE THREAD

**Issue by gunyakov** [IvanSafonov/plasma-wallpaper-snow#8]
Your repo is outdated and its not possible to install this plugin by console in latest Kubuntu and KDE. Requre to update repo to bi compatible with latest kubuntu.

**Comment by IvanSafonov** [comment]
Hi! Yes, the repository is basically abandoned. But it's quite easy to install this wallpaper. 
```bash
wget https://github.com/IvanSafonov/plasma-wallpaper-snow/archive/refs/heads/master.zip
unzip ./master.zip
mkdir -p ~/.local/share/plasma/wallpapers/
cp -r ./plasma-wallpaper-snow-master/snow ~/.local/share/plasma/wallpapers/org.kde.snow
```
And open or reopen desktop settings. Then you will find the new wallpaper type.

I'll try to upload it to https://store.kde.org/ later, so it would be possible to install this plugin from desktop settings with a couple of mouse clicks.
Didn't know it's still working and somebody wants to use it.
